### ISSUE TITLE
Restore and update an existing model card

### ISSUE THREAD

**Issue by Nithanaroy** [tensorflow/model-card-toolkit#109]
Thank you for creating and open sourcing this toolkit. It helped the entire team be on the same page much more easily. It also enabled us to review ML meta data more effectively. Is there a way to quickly restore an existing model card and update some textual sections like `model_card.model_parameters.model_architecture` without having to recreate more complex sections like `model_card.quantitative_analysis.graphics.collection`? This really helps address review comments much faster without having to recompute graphs / charts every time.

**Comment by timlrx** [comment]
We also encountered the same need and created our own model card creator, editor and viewer - https://report.verifyml.com/

It should be compatible with the current model card though there might be some differences over time. Here's the [breast cancer diagnostic model card](https://report.verifyml.com/redirect?url=https://github.com/cylynx/verifyml/tree/main/examples/model_card_output/data/breast_cancer_diagnostic_model_card.proto&section=modelDetails)

**Comment by codesue** [comment]
Hi @Nithanaroy, you can use `ModelCard` methods like `.copy_from_proto()`, `.from_json()`, and [similar methods](https://www.tensorflow.org/responsible_ai/model_card_toolkit/api_docs/python/model_card_toolkit/ModelCard) to restore a model card. There are some examples of how to use these methods in the [ModelCardToolkit source code](https://github.com/tensorflow/model-card-toolkit/blob/master/model_card_toolkit/core.py#L176-L183) and in [model_card_test.py](https://github.com/tensorflow/model-card-toolkit/blob/master/model_card_toolkit/model_card_test.py), but I don't believe this is documented yet. As a next step, we could add documentation on how to restore a model card as well as how to save a model card in a diff-able format, which was asked in about https://github.com/tensorflow/model-card-toolkit/discussions/232.
