### ISSUE TITLE
Dependencies issue with packages versions while installing model card toolkit

### ISSUE THREAD

**Issue by ehassan66** [tensorflow/model-card-toolkit#185]
## Expected Behavior
I want to install a model card toolkit in my python virtual environment through this command: **pip install model-card-toolkit**

## Actual Behavior
Model card toolkit should install successfully. 

## Steps to Reproduce the Problem

and I am facing this below issue, I have tried many times with different combinations but every time dependencies conflicts occurred. 

Collecting model-card-toolkit
ERROR: Cannot install model-card-toolkit==0.1.0, model-card-toolkit==0.1.1, model-card-toolkit==0.1.2, model-card-toolkit==0.1.3, model-card-toolkit==1.0.0, model-card-toolkit==1.1.0 and model-card-toolkit==1.2.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    model-card-toolkit 1.2.0 depends on tfx<1.6.0 and >=1.5.0
    model-card-toolkit 1.1.0 depends on ml-metadata<1.3.0 and >=1.2.0
    model-card-toolkit 1.0.0 depends on tensorflow-data-validation<0.27.0 and >=0.26.0
    model-card-toolkit 0.1.3 depends on tensorflow-data-validation<0.27.0 and >=0.26.0
    model-card-toolkit 0.1.2 depends on tensorflow-data-validation<0.27.0 and >=0.26.0
    model-card-toolkit 0.1.1 depends on absl-py<0.9 and >=0.7
    model-card-toolkit 0.1.0 depends on absl-py<0.9 and >=0.7

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

**I have these packages installed** 

    absl-py==1.0.0
    autopep8==1.6.0
    ml-metadata==0.13.1.dev0
    protobuf==3.19.3
    pycodestyle==2.8.0
    six==1.16.0
    toml==0.10.2

Can someone please help with which combination of packages should I have to install to resolve this issue? 

## Specifications

- Version:
- Platform:

**Comment by shuklak13** [comment]
Hi - we just release Model Card Toolkit v1.3. Can you attempt to re-install it and let us know if you still run into the resolution error?

**Comment by ehassan66** [comment]
Thank you so much @shuklak13 . I have install model card toolkit on python V3.6. Because on python 3.10 its create dependencies, issues with tensorflow.

**Comment by shuklak13** [comment]
If you are still facing issues with dependencies on the Model Card Toolkit install, please share your dependency versions, python version, and error message.

**Comment by ehassan66** [comment]
Dear Shukla,

Thank you so much for your response.


I was facing the dependency issue below when installing the model car toolkit "pip install model-card-toolkit"

ERROR: Cannot install model-card-toolkit==0.1.0, model-card-toolkit==0.1.1, model-card-toolkit==0.1.2, model-card-toolkit==0.1.3, model-card-toolkit==1.0.0 and model-card-toolkit==1.1.0 because these package versions have conflicting dependencies.


The conflict is caused by:

  *   model-card-toolkit 1.1.0 depends on ml-metadata<1.3.0 and >=1.2.0
  *

model-card-toolkit 1.0.0 depends on ml-metadata<0.27.0 and >=0.26.0

  *

model-card-toolkit 0.1.3 depends on ml-metadata<0.27.0 and >=0.26.0

  *

model-card-toolkit 0.1.2 depends on ml-metadata<0.27.0 and >=0.26.0

  *

model-card-toolkit 0.1.1 depends on tensorflow-data-validation<0.23 and >=0.21.0

  *

model-card-toolkit 0.1.0 depends on tensorflow-data-validation<0.23 and >=0.21.0

To fix this you could try to:

  1.  loosen the range of package versions you've specified
  2.  remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies


I was using Python V3.10, then I installed Python V3.6.4, so I have successfully installed the model card toolkit. But when I run the example of the model card toolkit with SciKit-learn on my jupyter notebook., I again faced the following error.

AttributeError: 'list' object has no attribute 'train'.
This error was located on last part where Annotate information into a model card on this line.

But when I run the same example on Google Colab it works fine. As in Google Colab Python V3.7.12.

The last part of Google Colab file and Jupyter notebook is different. As in the Jupyter Notebook, mctlib is not defined.

Can you please explain it to me or guide me through the above scenario? How I run the model card toolkit in my local machine and also with provided examples?

Thanks.
Regards:
MUhammad Hassan

________________________________

**Comment by shuklak13** [comment]
It sounds like your local Jupyter notebook and/or last installed version of model-card-toolkit is out of date. I would recommend re-downloading the notebook and re-installing model-card-toolkit.

**Comment by ehassan66** [comment]
Dear Shukla,

Thank you so much for your response.
Now I have exactly run the code as on Google colab and its working fine. So I go ahead with this. Actually, when I download the jupyter file from this link https://colab.research.google.com/github/tensorflow/model-card-toolkit/blob/master/model_card_toolkit/documentation/examples/Scikit_Learn_Model_Card_Toolkit_Demo.ipynb#scrollTo=tuOe1ymfHZPu
and run on my local jupyter notebook then its not run properly and display an error..
[https://colab.research.google.com/img/colab_favicon_256px.png]<https://colab.research.google.com/github/tensorflow/model-card-toolkit/blob/master/model_card_toolkit/documentation/examples/Scikit_Learn_Model_Card_Toolkit_Demo.ipynb#scrollTo=tuOe1ymfHZPu>
Google Colab<https://colab.research.google.com/github/tensorflow/model-card-toolkit/blob/master/model_card_toolkit/documentation/examples/Scikit_Learn_Model_Card_Toolkit_Demo.ipynb#scrollTo=tuOe1ymfHZPu>
Google Colab ... Sign in
colab.research.google.com


________________________________

**Comment by wardVD** [comment]
Haven't found a way to install this package without running into severe dependency issues. Can this be looked at asap?

**Comment by dakl** [comment]
I get the same installing using pipenv, in both python 3.8 and python 3.9. Is there anything I can do about that @shuklak13 ?
