### ISSUE TITLE
Does latest version (v1.3.0) support Python 3.9 or above? 

### ISSUE THREAD

**Issue by gatheluck** [tensorflow/model-card-toolkit#202]
Thank you for creating and open sourcing this cool toolkit. Currently I tried to pip install latest version (v1.3.0) of `model-card-toolkit` to Python 3.9 environment. Concretely speaking, I tried to build following simple dockerfile (Docker version 20.10.12, build e91ed57) at Ubuntu 20.04.

```Dockerfile
FROM python:3.9.10-slim
RUN pip3 model-card-toolkit==1.3.0
```

As a result, built failed and faced following error.

```bash
Sending build context to Docker daemon  9.216kB
Step 1/2 : FROM python:3.9.10-slim
 ---> 4acfa68b68bf
Step 2/2 : RUN pip3 install model-card-toolkit==1.3.0
 ---> Running in e4f291a180e7
Collecting model-card-toolkit==1.3.0
  Downloading model_card_toolkit-1.3.0-py3-none-any.whl (74 kB)
Collecting jinja2<3,>=2.10
  Downloading Jinja2-2.11.3-py2.py3-none-any.whl (125 kB)
Collecting matplotlib<4,>=3.2.0
  Downloading matplotlib-3.5.1-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.whl (11.2 MB)
Collecting tensorflow-metadata<1.6.0,>=1.5.0
  Downloading tensorflow_metadata-1.5.0-py3-none-any.whl (48 kB)
ERROR: Could not find a version that satisfies the requirement tfx<1.6.0,>=1.5.0 (from model-card-toolkit) (from versions: 0.13.0rc0, 0.13.0rc1, 0.13.0rc2, 0.13.0, 0.14.0rc1, 0.14.0, 0.15.0rc0, 0.15.0, 0.21.0rc0, 0.21.0, 0.21.1, 0.21.2, 0.21.3, 0.21.4, 0.21.5, 0.22.0rc0, 0.22.0, 0.22.1rc1, 0.22.1, 0.22.2, 0.23.0rc0, 0.23.0, 0.23.1)
ERROR: No matching distribution found for tfx<1.6.0,>=1.5.0
WARNING: You are using pip version 21.2.4; however, version 22.0.4 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
The command '/bin/sh -c pip3 install model-card-toolkit==1.3.0' returned a non-zero code: 1
```

I'm suspecting that this error is caused by Python requirement of `tfx`. According to `tfx` PyPI page, it requires `Python >=3.7, <3.9` (https://pypi.org/project/tfx/). And due to latest `model-card-toolkit` (v1.3.0) depends on `tfx`, it also needs `Python >=3.7, <3.9`. 
This is my current hypothesis about this error. However, the PyPI page of the `model-card-toolkit` says the Python requirements are >=3.6, <4 (https://pypi.org/project/model-card-toolkit/). So are there any way around this error? Thank you.

**Comment by shuklak13** [comment]
Hi - I believe you are correct. We depend on `tfx` which does not currently support Python 3.9. So `model-card-toolkit` will not be compatible with Python 3.9 until `tfx` is updated.

**Comment by gatheluck** [comment]
Thank you for your quick response @shuklak13 ! I understand the current situation. I look forward to `tfx`'s support for Python 3.9.

**Comment by codesue** [comment]
HI @gatheluck, there's a draft PR that will remove the `tfx` dependency when merged. I linked it to this issue.
