### ISSUE TITLE
Prevent empty objects from rendering as "None" 

### ISSUE THREAD

**Issue by codesue** [tensorflow/model-card-toolkit#213]
## Expected Behavior
Empty objects shouldn't be rendered when exporting model cards.

## Actual Behavior
Currently, empty objects render as "None" when exporting model cards. This happens because empty model card fields are truthy. For example, if you only want to render model details in a template if there are details and write: 
```
{% if model_details %}
    <h2>Model Details</h2>
    {{ model_details.overview }}
{% endif %}
``` 

you'd get:
```
Model Details
None
```

instead of nothing.

A workaround is to use `{% if model_details.to_dict() %}` instead. A possible solution is to implement `__bool__` for `BaseModelCardField`.

## Steps to Reproduce the Problem

Run the [MLMD Model Card Toolkit Demo](https://www.tensorflow.org/responsible_ai/model_card_toolkit/examples/MLMD_Model_Card_Toolkit_Demo#display_model_card)

![mc renders empty objects](https://user-images.githubusercontent.com/11793274/173406107-cd1629b8-a5ec-4614-b9d7-0ada76f54d6c.png)

(To clarify, the `None` in the graphics collection isn't related to this. I believe that's happening because there's no check for whether there's a graphics description in the `render_metrics_graphics(graphics)` macro.)

**Comment by bahadirery** [comment]
Hi, I am currently using the toolkit and facing the same problem. What should I exactly do the eliminate the rendering as 'none' ?

**Comment by codesue** [comment]
Hi @bahadirery, as a workaround, I changed `{% if model_details %}` to `{% if model_details.to_dict() %}` in my template. The [Model Card templates guide](https://www.tensorflow.org/responsible_ai/model_card_toolkit/guide/templates) has instructions on how to modify templates.

A possible fix is to implement `__bool__` for `BaseModelCardField`, but I haven't had a chance to try that out yet.

**Comment by bahadirery** [comment]
Thanks for the answer @codesue, however, I am still having issues with the tool.  I want to add custom fields and therefore I forked the repo and modified the .proto file, model_card.py, core.py, and the template of course. But I can not install the package from the source by following the instructions.  This is the error message I am getting.
<img width="665" alt="image" src="https://user-images.githubusercontent.com/115642717/203327083-52f2e422-136c-4aa8-9b72-e52c07226272.png">

I ran it on WSL on windows 11.

**Comment by bahadirery** [comment]
Hi @codesue, thanks for your answer. In the meantime, I solved the problem. I also could add some custom fields by forking the repo. However, somehow I can get rid of the `none` in the graphics collection. Will it be fixed in the next release?

**Comment by codesue** [comment]
Hi @bahadirery, most likely. For now, you can get rid of "None" in the graphics collection by changing `{{ graphics.description }}` to `{% if graphics.description %}<p>{{ graphics.description }}</p>{% endif %}` in the [render_metrics_graphics macro](https://github.com/tensorflow/model-card-toolkit/blob/master/model_card_toolkit/template/html/default_template.html.jinja#L82).

**Comment by bahadirery** [comment]
Hello @codesue , thanks for the help but that did not work. I even tried to delete the whole  `{{ graphics.description }}` line.

**Comment by Starborn** [comment]
Hay, can anyone assist?

*403.* That’s an error.

Your client does not have permission to get URL
/responsible_ai/model_card_toolkit/guide/templates from this server. That’s
all we know.

**Comment by codesue** [comment]
> Hello @codesue , thanks for the help but that did not work. I even tried to delete the whole `{{ graphics.description }}` line.

@bahadirery, could you share what your template and model card look like?

**Comment by codesue** [comment]
> Hay, can anyone assist?
>
> *403.* That’s an error.
>
> Your client does not have permission to get URL
> /responsible_ai/model_card_toolkit/guide/templates from this server. That’s
> all we know.

@Starborn, could you open a new issue detailing what happened, the steps to reproduce the problem, and how you're running your code (e.g. python script, Jupyter notebook on your local machine, Colab)?

**Comment by bahadirery** [comment]
Sure! here they are @codesue  :[template](https://github.com/bahadirery/model-card-toolkit/blob/11cd88b9eeaa1fca8921e8247f40965fccc6c9bd/model_card_toolkit/template/html/default_template.html.jinja),  [model_card](https://github.com/bahadirery/model-card-toolkit/blob/b040f2a31784a58ab1e130e92e7014fadd648571/model_card.html)

**Comment by bahadirery** [comment]
It is `model_card = mct.scaffold_assets()`. I tried to define a new template path and also changed the template in model_card_toolkit/template so that it copies the right one. But It doesn't work. That is okay though. I appreciate the help. I will add a code that modifies the html string that is created at the end. That will work hopefully.
