### ISSUE TITLE
Please add support for TFX 1.6.0

### ISSUE THREAD

**Issue by codesue** [tensorflow/model-card-toolkit#214]
Currently, model-card-toolkit specifies `tfx>=1.5.0,<1.6.0` as a requirement. Is it possible to relax this to allow `tfx==1.6.0`?

**Comment by casassg** [comment]
@rcrowe-google 👀

**Comment by rky0930** [comment]
I have the same issue. I want to use it with TFX 1.9 or later. Hope this issue gets resolved soon !
