### ISSUE TITLE
Version 2.0.0 not available in PyPi

### ISSUE THREAD

**Issue by alvaroazabal** [tensorflow/model-card-toolkit#263]
## Expected Behavior
Version 2.0.0 of the `model-card-toolkit` being available in PyPi

This issue https://github.com/tensorflow/model-card-toolkit/issues/247 removed the dependency on `tfx` and released a new version 2.0.0.

## Actual Behavior
The latest version of PyPi available is 1.3.2, which still depends on tfx.

## Steps to Reproduce the Problem
<img width="1109" alt="Screenshot 2023-03-06 at 17 30 47" src="https://user-images.githubusercontent.com/100139681/223186248-00f32c97-fa11-461a-bd05-994ce9a39477.png">

**Comment by codesue** [comment]
Hi @alvaroazabal, version 2.0.0 has not been released yet.

Adding @hanneshapke for an updated estimate on when it will be released.

**Comment by codesue** [comment]
Hi @alvaroazabal, version 2.0.0 is now available in PyPI: https://pypi.org/project/model-card-toolkit/2.0.0.
