### ISSUE TITLE
Migrate setup.py from distutils to setuptools

### ISSUE THREAD

**Issue by codesue** [tensorflow/model-card-toolkit#269]
`distutils` will be removed in Python 3.12 and there's an existing TODO to remove it from MCT's [setup.py](https://github.com/tensorflow/model-card-toolkit/blob/main/setup.py#L23).

Refer to PEP 632 for [migration advice](https://peps.python.org/pep-0632/#migration-advice).

**Comment by BhavyaBh289** [comment]
is this still active ?

**Comment by codesue** [comment]
Hi @BhavyaBh289, after looking into this some more, it seems there isn't a good `setuptools` alternative yet for `distutils.command.build`, and we can continue to use `distutils` through `setuptools`' bundled copy after it's removed from the standard library. See https://github.com/pypa/setuptools/issues/2928. This is still up for grabs, but the only work required now is to delete the TODO comment.
