### ISSUE TITLE
Allow tensorflow-model-analysis < 0.45 as a dependency

### ISSUE THREAD

**Issue by hanneshapke** [tensorflow/model-card-toolkit#288]
## Expected Behavior

The MCT dependency of TFMA < 0.42 is limiting the TFX Addons update of TFX dependency.

Details around the TFMA releases: https://github.com/tensorflow/model-analysis/releases
Changes with biggest impact on MCT:
* 0.44 drops Py3.7 support, requires TF >= 2.12, tfx-bsl>=1.13.0,<1.14.0
* 0.43 depends on tensorflow>=2.11,<3, tfx-bsl>=1.2.0,<1.13.0

**Questions**:
Which TF version should we support?
Should we make the TFMA dependency conditional to the underlying TF version?

**Comment by codesue** [comment]
Some additional questions from my end:

- Does block upgrades for all tfxa components or just the model card generator?
- Are there any workarounds?
- What's the requested timeline for this change?

**Comment by hanneshapke** [comment]
The way we test/build TFX Addons, it blocks all projects. TFXA installs `tfx`, the mct generator installs the `model-card-toolkit` which has it's own `tfma` dependency.

A workaround on the mct side would the conditional installation (depending on the `tf` version).

Timeline?
I think it is blocking the `tfx` upgrade for `tfx-addons` -> https://github.com/tensorflow/tfx-addons/pull/248

**Comment by codesue** [comment]
Got it! I don't have the capacity to take this on anytime soon, but I'm happy to review any pull requests.
