### ISSUE TITLE
!pip install model-card-toolkit --use-feature=2020-resolver command is running forever in Google Colab

### ISSUE THREAD

**Issue by sagu94271** [tensorflow/model-card-toolkit#5]
## Expected Behavior
package should be installed in few seconds and notebook should be able to execute the next cell.

## Actual Behavior
Google Colab is not installing the package.Notebook is running forever.

![image](https://user-images.githubusercontent.com/38607315/91656893-c9e1ef80-eabc-11ea-846e-0753e7a0c589.png)

## Steps to Reproduce the Problem

1.
2.
3.

## Specifications

- Version:
- Platform:

**Comment by fhuanming** [comment]
Hi, Would you mind trying install the package without flag "--use-feature=2020-resolver"?
