### ISSUE TITLE
hosted documentation

### ISSUE THREAD

**Issue by adrinjalali** [tensorflow/model-card-toolkit#73]
I was wondering if there's any plans to have the docs hosted somewhere like `readthedocs`.

**Comment by fhuanming** [comment]
Hi @adrinjalali, we have docs hosted on https://www.tensorflow.org/responsible_ai/model_card_toolkit/guide. Feel free to take a look.

**Comment by adrinjalali** [comment]
Thanks, that definitely helps :)

Are there plans to also include the API docs there?

**Comment by fhuanming** [comment]
cc @shuklak13 

Yes, the API docs is under a separate tab: https://www.tensorflow.org/responsible_ai/model_card_toolkit/api_docs/python/model_card_toolkit

**Comment by codesue** [comment]
Hi @adrinjalali, it looks like your question was answered, so I'm closing this issue. Feel free to reopen it if that's not the case. Thanks!
